version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es01
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 1g

  dejavu:
    image: appbaseio/dejavu
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - elastic

networks:
  elastic:
    external: true